[package]
name = "bevy_mod_edge_detection"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A simple plugin to add an edge detection shader to bevy"
repository = "https://github.com/IceSentry/bevy_mod_edge_detection"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
